### ISSUE TITLE
Usage API

### ISSUE THREAD

**Issue by detresed** [DeepLcom/deepl-dotnet#38] opened 2023-10-04 06:38 UTC
**Describe the bug**
The JSON (the props) of the useage API have been changed and running _translator.GetUsageAsync() only returns
{"Character":null,"Document":null,"TeamDocument":null,"AnyLimitReached":false}

**To Reproduce**
1.  _translator.GetUsageAsync()
2. check result, will be null

**Expected behavior**
I expect Character to be correctly filled with a value.

**Additional context**
Currently SDK uses characterCount new API name is character_count

**Comment by JanEbbing** [comment] 2023-10-04 07:11
Hi, sorry I can't reproduce this. The return value has always been in lower snake case, which we use to parse the JSON [here](https://github.com/DeepLcom/deepl-dotnet/blame/main/DeepL/Internal/JsonUtils.cs#L15-L16) (and have been for 2yrs). Could you provide more info how you're running your code? (`deepl-dotnet` version, Dotnet version etc).

With v1.7.1 of the library, the following code:

```dotnet

var translator = new Translator("d2bf17e9-5335-42e1-e0d4-437ab0dbee77");
var usage = await translator.GetUsageAsync();                
Console.WriteLine(usage.ToString());
```

Does not print nulls for me, but correctly returns the usage.

**Comment by detresed** [comment] 2023-10-04 08:48
I have found the issue on another place. The API has stopped sending the character_limit and only send character_count, resulting in Character being nulled.

**Comment by daniel-jones-deepl** [comment] 2023-10-11 20:18
I'd like to give an update: we've reproduced the problem and pinpointed the issue; we're working on a fix.

**Comment by daniel-jones-deepl** [comment] 2023-11-17 09:16
This issue should be fixed as of Oct 13.

**Closed by daniel-jones-deepl** 2023-11-17 09:16 UTC
Labels: bug
